[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$TemplatePath,

    [switch]$ExpectFailure
)

$ErrorActionPreference = "Stop"

function Add-Check {
    param(
        [System.Collections.Generic.List[object]]$Checks,
        [string]$Name,
        [bool]$Passed,
        [string]$Evidence
    )

    $Checks.Add([ordered]@{
        name = $Name
        passed = $Passed
        evidence = $Evidence
    }) | Out-Null
}

function Get-ComponentBlock {
    param(
        [string]$Yaml,
        [string]$DisplayName
    )

    $displayMatch = [regex]::Match($Yaml, "(?m)^\s{4}displayName: $([regex]::Escape($DisplayName))\s*$")
    if (-not $displayMatch.Success) {
        throw "Could not find component block for $DisplayName."
    }

    $startMarker = "  - kind: DialogComponent"
    $start = $Yaml.LastIndexOf($startMarker, $displayMatch.Index, [System.StringComparison]::Ordinal)
    if ($start -lt 0) {
        throw "Could not find component start for $DisplayName."
    }

    $next = $Yaml.IndexOf("`n$startMarker", $displayMatch.Index + $displayMatch.Length, [System.StringComparison]::Ordinal)
    if ($next -lt 0) {
        $next = $Yaml.Length
    }

    $Yaml.Substring($start, $next - $start).TrimEnd()
}

function Get-TriggerQueries {
    param([string]$ComponentBlock)

    $lines = $ComponentBlock -replace "`r`n", "`n" -replace "`r", "`n" -split "`n"
    $queries = [System.Collections.Generic.List[string]]::new()
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i].Trim() -ne "triggerQueries:") {
            continue
        }

        for ($j = $i + 1; $j -lt $lines.Count; $j++) {
            $line = $lines[$j]
            if ([string]::IsNullOrWhiteSpace($line)) {
                break
            }
            $match = [regex]::Match($line, "^[ \t]+- (?:`"(?<query>[^`"]+)`"|(?<query>.+?))[ \t]*$")
            if (-not $match.Success) {
                break
            }
            $queries.Add($match.Groups["query"].Value.Trim()) | Out-Null
        }
        break
    }

    @($queries)
}

function Test-StringArrayEqual {
    param([string[]]$Actual, [string[]]$Expected)

    if ($Actual.Count -ne $Expected.Count) {
        return $false
    }

    for ($i = 0; $i -lt $Expected.Count; $i++) {
        if ($Actual[$i] -ne $Expected[$i]) {
            return $false
        }
    }

    return $true
}

$resolvedTemplatePath = (Resolve-Path -LiteralPath $TemplatePath).Path
$yaml = Get-Content -LiteralPath $resolvedTemplatePath -Raw

$topicBlock = Get-ComponentBlock -Yaml $yaml -DisplayName "CriarTarefa"
$lowConfidenceBlock = Get-ComponentBlock -Yaml $yaml -DisplayName "LowConfidence"
$expectedTriggers = @(
    "criar tarefa",
    "nova tarefa",
    "adicionar tarefa",
    "cadastrar tarefa",
    "criar projeto",
    "novo projeto",
    "abrir projeto",
    "registrar projeto",
    "criar tarefa:",
    "abrir tarefa"
)
$actualTriggers = Get-TriggerQueries -ComponentBlock $topicBlock

$actionBlock = $null
try {
    $actionBlock = Get-ComponentBlock -Yaml $yaml -DisplayName "PMO_PA_CriarTarefa"
}
catch {
    $actionBlock = ""
}

$checks = [System.Collections.Generic.List[object]]::new()
Add-Check $checks "CriarTarefa is selectable by orchestrator" ($topicBlock -match "includeInOnSelectIntent:\s*true") "CriarTarefa includeInOnSelectIntent must be true."
Add-Check $checks "CriarTarefa has exact trigger contract" (Test-StringArrayEqual -Actual $actualTriggers -Expected $expectedTriggers) ("Actual triggers: " + ($actualTriggers -join ", "))
Add-Check $checks "LowConfidence advertises CriarTarefa" ($lowConfidenceBlock -match "criar tarefa/projeto") "Fallback message must list criar tarefa/projeto."
Add-Check $checks "CriarTarefa does not ask for ProjectID" ($topicBlock -notmatch "id:\s*ask_projectid|variable:\s*Topic\.ProjectID\b") "ProjectID is generated by the flow."
Add-Check $checks "CriarTarefa does not set stale ProjectID global" ($topicBlock -notmatch "id:\s*set_global_projectid|Global\.PMO_Criar_ProjectID") "Stale ProjectID global must not be set."
Add-Check $checks "CriarTarefa calls PMO_PA_CriarTarefa action" ($topicBlock -match "(?ms)id:\s*call_criar_tarefa.*?dialog:\s*(template-content|pmo_AssistentePMO)\.action\.PMO_PA_CriarTarefa") "Confirmed branch must invoke the action."
Add-Check $checks "CriarTarefa avoids fragile output binding" (($topicBlock -notmatch "(?ms)id:\s*call_criar_tarefa.*?output:\s*") -and ($topicBlock -notmatch "Topic\.message|Topic\.ProjectIDGerado|Topic\.CriarSuccess|Topic\.CriarErrorCode")) "Topic Checker rejects stale action output bindings; topic must call the action without output binding aliases."
Add-Check $checks "Action exposes expected input contract" (($actionBlock -match "propertyName:\s*nomeProjeto") -and ($actionBlock -match "propertyName:\s*titulo") -and ($actionBlock -match "propertyName:\s*responsavel") -and ($actionBlock -match "propertyName:\s*prazo") -and ($actionBlock -match "propertyName:\s*horas") -and ($actionBlock -match "propertyName:\s*prioridade")) "Action inputs must match flow trigger schema."
Add-Check $checks "Action exposes result output contract" ($actionBlock -match "propertyName:\s*result") "Action must expose result output."

$failed = @($checks | Where-Object { -not $_.passed })
$result = [ordered]@{
    templatePath = $resolvedTemplatePath
    expectedFailureMode = [bool]$ExpectFailure
    passed = ($failed.Count -eq 0)
    failedCheckCount = $failed.Count
    checks = $checks
}

$result | ConvertTo-Json -Depth 10

if ($ExpectFailure) {
    if ($failed.Count -eq 0) {
        throw "Expected failure, but all checks passed."
    }
    exit 0
}

if ($failed.Count -gt 0) {
    throw "CriarTarefa contract test failed: $($failed.name -join '; ')"
}
