#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codex.Phd.ComponentType
{
	
	
	/// <summary>
	/// Todos los tipos de componentes posibles para las soluciones.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum componenttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entidad = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Atributo = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Relacin = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Valordelistadesplegabledeatributos = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Valordebsquedadeatributos = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Veratributo = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Etiquetalocalizada = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Condicinadicionaldelarelacin = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conjuntodeopciones = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Relacindeentidad = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rolderelacindeentidad = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Relacionesderelacindeentidad = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Propiedadadministrada = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Clavedeentidad = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Privilegio = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrivilegeObjectTypeCode = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rol = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Privilegioderoles = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mostrarcadena = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Asignacindecadenaparamostrar = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Formulario = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organizacin = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultaguardada = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Flujodetrabajo = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Informe = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entidaddeinforme = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Categoradeinforme = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Visibilidaddelinforme = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Datosadjuntos = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Plantilladecorreoelectrnico = 36,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Plantilladecontrato = 37,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PlantilladeartculodeKB = 38,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Plantilladecombinacindecorrespondencia = 39,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Regladeduplicados = 44,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Condicinderegladeduplicados = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Asignacindeentidad = 46,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Asignacindeatributo = 47,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Comandodelacintadeopciones = 48,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Grupocontextualdelacintadeopciones = 49,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Personalizacindelacintadeopciones = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Regladelacintadeopciones = 52,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Asignacindefichadelacintadeopcionesacomando = 53,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Diferenciadelacintadeopciones = 55,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Visualizacindelaconsultaguardada = 59,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Formulariodelsistema = 60,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recursoweb = 61,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mapadelsitio = 62,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Roldeconexin = 63,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Controlcomplejo = 64,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Perfildeseguridaddecampo = 70,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Permisodecampo = 71,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tipodecomplemento = 90,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ensambladodecomplementos = 91,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PasodeprocesamientodelmensajedeSDK = 92,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImagendelpasodeprocesamientodelmensajedeSDK = 93,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Extremodeservicio = 95,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Regladeenrutamiento = 150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Elementoderegladeenrutamiento = 151,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLA = 152,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ElementodeSLA = 153,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Regladeconversin = 154,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Elementoderegladeconversin = 155,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Regladejerarqua = 65,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PerfildeMobileOffline = 161,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ElementodeperfildeMobileOffline = 162,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Regladesimilitud = 165,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Controlpersonalizado = 66,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Configuracinpredeterminadadelcontrolpersonalizado = 68,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Asignacindeorigendedatos = 166,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessage = 201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SDKMessageFilter = 202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessagePair = 203,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageRequest = 204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageRequestField = 205,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageResponse = 206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SdkMessageResponseField = 207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebWizard = 210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ndice = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Asignacindeimportacin = 208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Aplicacindelienzo = 300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conector = 371,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conector1 = 372,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Definicindevariabledeentorno = 380,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Valordelavariabledeentorno = 381,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TipodeproyectodeIA = 400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProyectodeIA = 401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConfiguracindeIA = 402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Configuracindeanlisisdeentidades = 430,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Configuracindelaimagendeatributo = 431,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Configuracindelaimagendeentidad = 432,
	}
}
#pragma warning restore CS1591
