#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum botcomponent_componenttype
{
	
	/// <summary>
	/// A topic defines a how a bot conversation plays out. A topic has trigger phrases - these are phrases, keywords, or questions - and conversation nodes - these are what you use to define how a bot should respond and what it should do.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Tema = 0,
	
	/// <summary>
	/// Power Virtual Agents enables you to extend your bot using Bot Framework Skills. Bot Framework Skills are re-usable conversational skill building-blocks covering conversational use-cases.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Aptitud = 1,
	
	/// <summary>
	/// Variables let you save responses from your customers in a conversation with your bot so that you can reuse them later in the conversation.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Variabledebot = 2,
	
	/// <summary>
	/// An entity can be viewed as an information unit that represents a certain type of a real-world subject, like a phone number, zip code, city, or even a person's name.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Entidaddebot = 3,
	
	/// <summary>
	/// Dialogs provide more advanced functionality than topics and integrate with Bot Framework Composer.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Dilogo = 4,
	
	/// <summary>
	/// Language Understanding (LU) is used by a bot to understand language naturally and contextually to determine what next to do in a conversation flow.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Comprensindelidioma = 6,
	
	/// <summary>
	/// Language Generation (LG) lets you define multiple variations of a phrase, execute simple expressions based on context, and refer to conversational memory.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Generacindeidioma = 7,
	
	/// <summary>
	/// Trigger defines how the topic is triggered and/or what actions are executed.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Desencadenador = 5,
	
	/// <summary>
	/// Schema of the dialog that specifies dialog's input and output parameters
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Esquemadedilogo = 8,
	
	/// <summary>
	/// A topic defines a how a bot conversation plays out. A topic has trigger phrases - these are phrases, keywords, or questions - and conversation nodes - these are what you use to define how a bot should respond and what it should do.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Tema_V2 = 9,
	
	/// <summary>
	/// Bot translations (V2)
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Traduccionesdebots_V2 = 10,
	
	/// <summary>
	/// An entity can be viewed as an information unit that represents a certain type of a real-world subject, like a phone number, zip code, city, or even a person's name.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Entidaddebot_V2 = 11,
	
	/// <summary>
	/// Variables let you save responses from your customers in a conversation with your bot so that you can reuse them later in the conversation.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Variabledebot_V2 = 12,
	
	/// <summary>
	/// Power Virtual Agents enables you to extend your bot using Bot Framework Skills. Bot Framework Skills are re-usable conversational skill building-blocks covering conversational use-cases.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Capacidad_V2 = 13,
	
	/// <summary>
	/// File attachments enable you to extend your bot with file content
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Datosadjuntosaarchivosdebots = 14,
	
	/// <summary>
	/// A Custom GPT to answer customer queries in Copilot.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	GPTpersonalizado = 15,
	
	/// <summary>
	/// A knowledge source enables to query/search over content configured.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Origendeconocimientos = 16,
	
	/// <summary>
	/// An external trigger to trigger copilot
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Desencadenadorexterno = 17,
	
	/// <summary>
	/// Copilot settings stored per language.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Configuracindecopiloto = 18,
	
	/// <summary>
	/// Test Case for Agent validation
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Casodeprueba = 19,
	
	/// <summary>
	/// A Custom Metric Definition allows to define a metric to track.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	CustomMetricDefinition = 20,
}

/// <summary>
/// Estado del BotComponent
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum botcomponent_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Razón para el estado del BotComponent
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum botcomponent_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Activo = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactivo = 2,
}

/// <summary>
/// Contiene los componentes clave de creación de un copiloto como temas, entidades, variables, etc.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("botcomponent")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class botcomponent : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public botcomponent() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "botcomponent";
	
	public const string EntityLogicalCollectionName = "botcomponents";
	
	public const string EntitySetName = "botcomponents";
	
	public const int EntityTypeCode = 10163;
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Color de énfasis de este componente reutilizable
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accentcolor")]
	public string AccentColor
	{
		get
		{
			return this.GetAttributeValue<string>("accentcolor");
		}
		set
		{
			this.OnPropertyChanging("AccentColor");
			this.SetAttributeValue("accentcolor", value);
			this.OnPropertyChanged("AccentColor");
		}
	}
	
	/// <summary>
	/// Identificador único de instancias de entidad
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("botcomponentid")]
	public System.Nullable<System.Guid> botcomponentId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("botcomponentid");
		}
		set
		{
			this.OnPropertyChanging("botcomponentId");
			this.SetAttributeValue("botcomponentid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("botcomponentId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("botcomponentid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.botcomponentId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canmodifystate")]
	public System.Nullable<bool> canmodifystate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("canmodifystate");
		}
		set
		{
			this.OnPropertyChanging("canmodifystate");
			this.SetAttributeValue("canmodifystate", value);
			this.OnPropertyChanged("canmodifystate");
		}
	}
	
	/// <summary>
	/// La categoría del componente de copiloto.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("category")]
	public string Category
	{
		get
		{
			return this.GetAttributeValue<string>("category");
		}
		set
		{
			this.OnPropertyChanging("Category");
			this.SetAttributeValue("category", value);
			this.OnPropertyChanged("Category");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	/// <summary>
	/// El subtipo del componente de copiloto.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componenttype")]
	public virtual botcomponent_componenttype? ComponentType
	{
		get
		{
			return ((botcomponent_componenttype?)(EntityOptionSetEnum.GetEnum(this, "componenttype")));
		}
		set
		{
			this.OnPropertyChanging("ComponentType");
			this.SetAttributeValue("componenttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("ComponentType");
		}
	}
	
	/// <summary>
	/// Contenido o metadatos del componente de bot que define su estructura y propiedades.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("content")]
	public string Content
	{
		get
		{
			return this.GetAttributeValue<string>("content");
		}
		set
		{
			this.OnPropertyChanging("Content");
			this.SetAttributeValue("content", value);
			this.OnPropertyChanged("Content");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario que creó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Fecha y hora de creación del registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario delegado que creó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// El contenido del componente de bot en formato de OBI
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("data")]
	public string Data
	{
		get
		{
			return this.GetAttributeValue<string>("data");
		}
		set
		{
			this.OnPropertyChanging("Data");
			this.SetAttributeValue("data", value);
			this.OnPropertyChanged("Data");
		}
	}
	
	/// <summary>
	/// Se utiliza para almacenar dependencias entre bots.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencies")]
	public string Dependencies
	{
		get
		{
			return this.GetAttributeValue<string>("dependencies");
		}
		set
		{
			this.OnPropertyChanging("Dependencies");
			this.SetAttributeValue("dependencies", value);
			this.OnPropertyChanged("Dependencies");
		}
	}
	
	/// <summary>
	/// Contiene texto en el que se pueden realizar búsquedas del componente de bot
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
	public string Description
	{
		get
		{
			return this.GetAttributeValue<string>("description");
		}
		set
		{
			this.OnPropertyChanging("Description");
			this.SetAttributeValue("description", value);
			this.OnPropertyChanged("Description");
		}
	}
	
	/// <summary>
	/// Este es un atributo de tipo de archivo para almacenar archivos adjuntos.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filedata")]
	public System.Nullable<System.Guid> FileData
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("filedata");
		}
	}
	
	/// <summary>
	/// Vínculo para obtener más información sobre este componente
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("helplink")]
	public string HelpLink
	{
		get
		{
			return this.GetAttributeValue<string>("helplink");
		}
		set
		{
			this.OnPropertyChanging("HelpLink");
			this.SetAttributeValue("helplink", value);
			this.OnPropertyChanged("HelpLink");
		}
	}
	
	/// <summary>
	/// Dirección URL del icono de este componente
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iconurl")]
	public string IconUrl
	{
		get
		{
			return this.GetAttributeValue<string>("iconurl");
		}
		set
		{
			this.OnPropertyChanging("IconUrl");
			this.SetAttributeValue("iconurl", value);
			this.OnPropertyChanged("IconUrl");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// Idioma del componente de copiloto
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("language")]
	public virtual chatbotlanguage? Language
	{
		get
		{
			return ((chatbotlanguage?)(EntityOptionSetEnum.GetEnum(this, "language")));
		}
		set
		{
			this.OnPropertyChanging("Language");
			this.SetAttributeValue("language", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("Language");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario que modificó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Fecha y hora en que se modificó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario delegado que modificó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// El nombre de la entidad personalizada.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
		set
		{
			this.OnPropertyChanging("name");
			this.SetAttributeValue("name", value);
			this.OnPropertyChanged("name");
		}
	}
	
	/// <summary>
	/// Fecha y hora en que se migró el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Identificador del propietario
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Identificador único de la unidad de negocio propietaria del registro
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Identificador único del equipo propietario del registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario propietario del registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Identificador único de la colección de componentes de copiloto asociada al componente de copiloto.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentbotcomponentcollectionid")]
	public Microsoft.Xrm.Sdk.EntityReference ParentBotComponentCollectionId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentbotcomponentcollectionid");
		}
		set
		{
			this.OnPropertyChanging("ParentBotComponentCollectionId");
			this.SetAttributeValue("parentbotcomponentcollectionid", value);
			this.OnPropertyChanged("ParentBotComponentCollectionId");
		}
	}
	
	/// <summary>
	/// Identificador único del componente de copiloto asociado al componente de copiloto.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentbotcomponentid")]
	public Microsoft.Xrm.Sdk.EntityReference ParentBotComponentId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentbotcomponentid");
		}
		set
		{
			this.OnPropertyChanging("ParentBotComponentId");
			this.SetAttributeValue("parentbotcomponentid", value);
			this.OnPropertyChanged("ParentBotComponentId");
		}
	}
	
	/// <summary>
	/// Identificador único del bot asociado al componente.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentbotid")]
	public Microsoft.Xrm.Sdk.EntityReference ParentBotId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentbotid");
		}
		set
		{
			this.OnPropertyChanging("ParentBotId");
			this.SetAttributeValue("parentbotid", value);
			this.OnPropertyChanged("ParentBotId");
		}
	}
	
	/// <summary>
	/// Directiva de reutilización para el componente de copiloto
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("reusepolicy")]
	public virtual botcomponentreusepolicy? ReusePolicy
	{
		get
		{
			return ((botcomponentreusepolicy?)(EntityOptionSetEnum.GetEnum(this, "reusepolicy")));
		}
		set
		{
			this.OnPropertyChanging("ReusePolicy");
			this.SetAttributeValue("reusepolicy", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("ReusePolicy");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("schemaname")]
	public string SchemaName
	{
		get
		{
			return this.GetAttributeValue<string>("schemaname");
		}
		set
		{
			this.OnPropertyChanging("SchemaName");
			this.SetAttributeValue("schemaname", value);
			this.OnPropertyChanged("SchemaName");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Estado del BotComponent
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual botcomponent_statecode? statecode
	{
		get
		{
			return ((botcomponent_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Razón para el estado del BotComponent
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual botcomponent_statuscode? statuscode
	{
		get
		{
			return ((botcomponent_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// Solo para uso interno.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Código de la zona horaria que estaba en uso cuando se creó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N botcomponent_parent_botcomponent
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("botcomponent_parent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<botcomponent> Referencedbotcomponent_parent_botcomponent
	{
		get
		{
			return this.GetRelatedEntities<botcomponent>("botcomponent_parent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedbotcomponent_parent_botcomponent");
			this.SetRelatedEntities<botcomponent>("botcomponent_parent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedbotcomponent_parent_botcomponent");
		}
	}
	
	/// <summary>
	/// N:N botcomponent_botcomponent
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("botcomponent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public System.Collections.Generic.IEnumerable<botcomponent> Referencingbotcomponent_botcomponent
	{
		get
		{
			return this.GetRelatedEntities<botcomponent>("botcomponent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingbotcomponent_botcomponent");
			this.SetRelatedEntities<botcomponent>("botcomponent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingbotcomponent_botcomponent");
		}
	}
	
	/// <summary>
	/// N:N botcomponent_botcomponent
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("botcomponent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<botcomponent> Referencedbotcomponent_botcomponent
	{
		get
		{
			return this.GetRelatedEntities<botcomponent>("botcomponent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedbotcomponent_botcomponent");
			this.SetRelatedEntities<botcomponent>("botcomponent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedbotcomponent_botcomponent");
		}
	}
	
	/// <summary>
	/// N:N botcomponent_connectionreference
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("botcomponent_connectionreference")]
	public System.Collections.Generic.IEnumerable<connectionreference> botcomponent_connectionreference
	{
		get
		{
			return this.GetRelatedEntities<connectionreference>("botcomponent_connectionreference", null);
		}
		set
		{
			this.OnPropertyChanging("botcomponent_connectionreference");
			this.SetRelatedEntities<connectionreference>("botcomponent_connectionreference", null, value);
			this.OnPropertyChanged("botcomponent_connectionreference");
		}
	}
	
	/// <summary>
	/// N:1 botcomponent_parent_botcomponent
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentbotcomponentid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("botcomponent_parent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public botcomponent Referencingbotcomponent_parent_botcomponent
	{
		get
		{
			return this.GetRelatedEntity<botcomponent>("botcomponent_parent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingbotcomponent_parent_botcomponent");
			this.SetRelatedEntity<botcomponent>("botcomponent_parent_botcomponent", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingbotcomponent_parent_botcomponent");
		}
	}
}
#pragma warning restore CS1591
