#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("botcomponent_workflow")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class botcomponent_workflow : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public botcomponent_workflow() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "botcomponent_workflow";
	
	public const string EntityLogicalCollectionName = null;
	
	public const string EntitySetName = "botcomponent_workflowset";
	
	public const int EntityTypeCode = 10169;
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("botcomponent_workflowid")]
	public System.Nullable<System.Guid> botcomponent_workflowId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("botcomponent_workflowid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("botcomponent_workflowid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			base.Id = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("botcomponentid")]
	public System.Nullable<System.Guid> botcomponentid
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("botcomponentid");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowid")]
	public System.Nullable<System.Guid> workflowid
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("workflowid");
		}
	}
	
	/// <summary>
	/// N:N botcomponent_workflow
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("botcomponent_workflow")]
	public System.Collections.Generic.IEnumerable<botcomponent> botcomponent_workflow1
	{
		get
		{
			return this.GetRelatedEntities<botcomponent>("botcomponent_workflow", null);
		}
		set
		{
			this.OnPropertyChanging("botcomponent_workflow1");
			this.SetRelatedEntities<botcomponent>("botcomponent_workflow", null, value);
			this.OnPropertyChanged("botcomponent_workflow1");
		}
	}
}
#pragma warning restore CS1591
