#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// This field configures how this connection reference gets prompted
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum connectionreference_promptingbehavior
{
	
	/// <summary>
	/// Prompt to provide a connection for this reference during import
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Promptonimport = 0,
	
	/// <summary>
	/// Skip all prompting behavior. Used for Invoker based Connection References
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Skip = 1,
}

/// <summary>
/// Estado de la referencia de conexión
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum connectionreference_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Razón para el estado de la referencia de conexión
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum connectionreference_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Activa = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactiva = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("connectionreference")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class connectionreference : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public connectionreference() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "connectionreference";
	
	public const string EntityLogicalCollectionName = "connectionreferences";
	
	public const string EntitySetName = "connectionreferences";
	
	public const int EntityTypeCode = 10120;
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	/// <summary>
	/// Identificador de la conexión en el centro de API
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionid")]
	public string ConnectionId
	{
		get
		{
			return this.GetAttributeValue<string>("connectionid");
		}
		set
		{
			this.OnPropertyChanging("ConnectionId");
			this.SetAttributeValue("connectionid", value);
			this.OnPropertyChanged("ConnectionId");
		}
	}
	
	/// <summary>
	/// Parámetros de conexión que se pueden reutilizar al crear conexiones en Microsoft Copilot Studio
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionparametersconfig")]
	public string ConnectionParametersConfig
	{
		get
		{
			return this.GetAttributeValue<string>("connectionparametersconfig");
		}
		set
		{
			this.OnPropertyChanging("ConnectionParametersConfig");
			this.SetAttributeValue("connectionparametersconfig", value);
			this.OnPropertyChanged("ConnectionParametersConfig");
		}
	}
	
	/// <summary>
	/// El conjunto de parámetros de conexión que se pueden reutilizar al crear conexiones en Microsoft Copilot Studio
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionparametersetconfig")]
	public string ConnectionParameterSetConfig
	{
		get
		{
			return this.GetAttributeValue<string>("connectionparametersetconfig");
		}
		set
		{
			this.OnPropertyChanging("ConnectionParameterSetConfig");
			this.SetAttributeValue("connectionparametersetconfig", value);
			this.OnPropertyChanged("ConnectionParameterSetConfig");
		}
	}
	
	/// <summary>
	/// Nombre de la referencia de conexión
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionreferencedisplayname")]
	public string connectionreferencedisplayname
	{
		get
		{
			return this.GetAttributeValue<string>("connectionreferencedisplayname");
		}
		set
		{
			this.OnPropertyChanging("connectionreferencedisplayname");
			this.SetAttributeValue("connectionreferencedisplayname", value);
			this.OnPropertyChanged("connectionreferencedisplayname");
		}
	}
	
	/// <summary>
	/// Identificador único de instancias de entidad
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionreferenceid")]
	public System.Nullable<System.Guid> connectionreferenceId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("connectionreferenceid");
		}
		set
		{
			this.OnPropertyChanging("connectionreferenceId");
			this.SetAttributeValue("connectionreferenceid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("connectionreferenceId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionreferenceid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.connectionreferenceId = value;
		}
	}
	
	/// <summary>
	/// Nombre único de referencia de conexión
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectionreferencelogicalname")]
	public string ConnectionReferenceLogicalName
	{
		get
		{
			return this.GetAttributeValue<string>("connectionreferencelogicalname");
		}
		set
		{
			this.OnPropertyChanging("ConnectionReferenceLogicalName");
			this.SetAttributeValue("connectionreferencelogicalname", value);
			this.OnPropertyChanged("ConnectionReferenceLogicalName");
		}
	}
	
	/// <summary>
	/// Identificador del conector público/compartido
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("connectorid")]
	public string ConnectorId
	{
		get
		{
			return this.GetAttributeValue<string>("connectorid");
		}
		set
		{
			this.OnPropertyChanging("ConnectorId");
			this.SetAttributeValue("connectorid", value);
			this.OnPropertyChanged("ConnectorId");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario que creó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Fecha y hora de creación del registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario delegado que creó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Buscar la entidad de conector
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customconnectorid")]
	public Microsoft.Xrm.Sdk.EntityReference CustomConnectorId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("customconnectorid");
		}
		set
		{
			this.OnPropertyChanging("CustomConnectorId");
			this.SetAttributeValue("customconnectorid", value);
			this.OnPropertyChanged("CustomConnectorId");
		}
	}
	
	/// <summary>
	/// Descripción de la referencia de conexión
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
	public string Description
	{
		get
		{
			return this.GetAttributeValue<string>("description");
		}
		set
		{
			this.OnPropertyChanging("Description");
			this.SetAttributeValue("description", value);
			this.OnPropertyChanged("Description");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario que modificó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Fecha y hora en que se modificó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario delegado que modificó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Fecha y hora en que se migró el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Identificador del propietario
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Identificador único de la unidad de negocio propietaria del registro
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Identificador único del equipo propietario del registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Identificador único del usuario propietario del registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// The Prompting Behavior for this connection reference
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("promptingbehavior")]
	public virtual connectionreference_promptingbehavior? PromptingBehavior
	{
		get
		{
			return ((connectionreference_promptingbehavior?)(EntityOptionSetEnum.GetEnum(this, "promptingbehavior")));
		}
		set
		{
			this.OnPropertyChanging("PromptingBehavior");
			this.SetAttributeValue("promptingbehavior", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("PromptingBehavior");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Estado de la referencia de conexión
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual connectionreference_statecode? statecode
	{
		get
		{
			return ((connectionreference_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Razón para el estado de la referencia de conexión
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual connectionreference_statuscode? statuscode
	{
		get
		{
			return ((connectionreference_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// Solo para uso interno.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Código de la zona horaria que estaba en uso cuando se creó el registro.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:N botcomponent_connectionreference
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("botcomponent_connectionreference")]
	public System.Collections.Generic.IEnumerable<botcomponent> botcomponent_connectionreference
	{
		get
		{
			return this.GetRelatedEntities<botcomponent>("botcomponent_connectionreference", null);
		}
		set
		{
			this.OnPropertyChanging("botcomponent_connectionreference");
			this.SetRelatedEntities<botcomponent>("botcomponent_connectionreference", null, value);
			this.OnPropertyChanged("botcomponent_connectionreference");
		}
	}
}
#pragma warning restore CS1591
