#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Tipo de directiva de reutilización asociada a componentes de copiloto de Copilot Studio.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum botcomponentreusepolicy
{
	
	/// <summary>
	/// No reutilizable. De forma predeterminada, un componente de copiloto no se puede reutilizar y la directiva de reutilización es Ninguna
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ninguna = 0,
	
	/// <summary>
	/// Es necesaria para uno o más componentes de copiloto públicos, pero no es invocable o visible directamente
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Privada = 1,
	
	/// <summary>
	/// Componente de copiloto compartido/reutilizable visible para su uso en todos los bots del entorno
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Pblica = 2,
}
#pragma warning restore CS1591
