#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum chatbotlanguage
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ingls = 1033,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Espaol = 1034,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Portugus_Brasil = 1046,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Francs = 1036,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Neerlands = 1043,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Noruego = 1044,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Dans = 1030,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Sueco = 1053,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Italiano = 1040,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Alemn = 1031,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Chino_simplificado = 2052,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Chino_tradicional = 1028,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	rabe = 1025,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Japons = 1041,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Coreano = 1042,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Hindi = 1081,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Indonesio = 1057,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ruso = 1049,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Polaco = 1045,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Turco = 1055,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Tailands = 1054,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Fins = 1035,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Griego = 1032,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Checo = 1029,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ingls_ReinoUnido = 2057,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Francs_Canad = 3084,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Espaol_EstadosUnidos = 21514,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ingls_Australia = 3081,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Hebreo = 1037,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Portugus_Portugal = 2070,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Spanish_PuertoRico = 20490,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Hungarian = 1038,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ukrainian = 1058,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Lithuanian = 1063,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Romanian = 1048,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Latvian = 1062,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Estonian = 1061,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Slovenian = 1060,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Vietnamese = 1066,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Croatian = 1050,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Bulgarian = 1026,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Slovak = 1051,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Catalan = 1027,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Basque = 1069,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Galician = 1110,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Kazakh = 1087,
}
#pragma warning restore CS1591
