#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Estado de este componente.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum componentstate
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Publicado = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Sinpublicar = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Eliminado = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Eliminadossinpublicar = 3,
}
#pragma warning restore CS1591
